name: Deploy assets
on:
  push:
    branches:
    - master
jobs:
  assets:
    name: Push to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress.org plugin asset/readme update
        uses: wearerequired/action-wordpress-plugin-asset-update@cc639dd # https://github.com/10up/action-wordpress-plugin-asset-update/issues/12#issuecomment-733592465
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ secrets.SLUG }}